E2E-graph: &E2E-graph
  task_level: e2e_graph
  dataset_splitter: Graph_splitter
  preprocess: null
  construct: ConstructMolCls
  args:
    walk_length: null
  eval_mode: max

Molecule_graph: &Molecule_graph
  <<: *E2E-graph
  task_name: Base_classification
  dataset_name: small_molecule
  process_label_func: process_binary_label
  eval_metric: auc
  eval_func: binary_auc_func
  num_classes: -1

