E2E-graph: &E2E-graph
  task_level: e2e_graph
  eval_pool_mode: mean
  eval_set_constructs:
    - stage: train
      split_name: train
    - stage: valid
      split_name: valid
    - stage: test
      split_name: test
    - stage: test
      split_name: train
    - stage: test
      split_name: valid


Task4: &Task4
# 任务4：光谱对应物质的化学分类
  <<: *E2E-graph
  task_name: Spectral_Classification
  dataset_name: Small_Molecule


